### ISSUE TITLE
Create basic money tracking mechanic

### ISSUE THREAD

**Issue by brittanyellich** [knot-games/cloud-tycoon#34]
As a user, I need to understand how much money revenue, cost, and profit I'm currently gaining each month.

- [x] Users have a set amount of money that they currently have
- [x] Each month, users gain revenue
- [x] Each month, users pay costs
- [x] Each month, the monthly profit is tracked against the goal for that level
- [ ] If a user exceeds the amount that is the goal for the level they are led to the next level

**Dependencies:**

- https://github.com/knot-games/cloud-tycoon/issues/16

Epic: https://github.com/knot-games/cloud-tycoon/issues/22
